# Generated by Django 4.2.27 on 2026-04-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
