# Generated by Django 4.2.27 on 2026-04-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_delete_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date', 'time']},
        ),
    ]
