# Generated by Django 6.0 on 2025-12-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hours', models.DecimalField(decimal_places=1, default=8.0, help_text='Target sleep hours per night', max_digits=3)),
                ('target_bedtime', models.TimeField(help_text='Target bedtime')),
                ('target_wake_time', models.TimeField(help_text='Target wake time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date you went to bed')),
                ('bedtime', models.TimeField()),
                ('wake_time', models.TimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Total sleep duration in hours', max_digits=4)),
                ('quality', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Below Average'), (4, 'Fair'), (5, 'Average'), (6, 'Good'), (7, 'Very Good'), (8, 'Great'), (9, 'Excellent'), (10, 'Perfect')], help_text='Rate your sleep quality 1-10')),
                ('fell_asleep_minutes', models.IntegerField(blank=True, help_text='Time taken to fall asleep in minutes', null=True)),
                ('times_woken', models.IntegerField(default=0, help_text='Number of times you woke up')),
                ('had_caffeine', models.BooleanField(default=False)),
                ('had_alcohol', models.BooleanField(default=False)),
                ('exercised', models.BooleanField(default=False)),
                ('stressed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SleepNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
