# Generated by Django 4.2.27 on 2026-02-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sleeplog',
            unique_together=set(),
        ),
    ]
