# Generated by Django 4.2.27 on 2026-04-03 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleep', '0003_alter_sleeplog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sleeplog',
            unique_together={('user', 'date')},
        ),
    ]
