# Generated by Django 4.2.27 on 2026-04-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0004_alter_sleeplog_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SleepNote',
        ),
    ]
