# Generated by Django 4.2.27 on 2026-04-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_water_goal_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
