# Generated by Django 4.2.27 on 2026-04-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_widgets',
            field=models.JSONField(default=list),
        ),
    ]
